local fishList = {
    -- COMMON
    {name="Salmon", min=100, max=180, weight=20, strength=30, rarity="Common"},
    {name="Trout", min=60, max=140, weight=25, strength=25, rarity="Common"},
    {name="Bass", min=70, max=160, weight=20, strength=35, rarity="Common"},
    {name="Carp", min=30, max=80, weight=30, strength=20, rarity="Common"},
    {name="Goldfish", min=5, max=20, weight=8, strength=10, rarity="Common"},
    {name="Mackerel", min=40, max=90, weight=10, strength=15, rarity="Common"},
    {name="Snapper", min=60, max=130, weight=15, strength=25, rarity="Common"},
    {name="Perch", min=20, max=50, weight=5, strength=10, rarity="Common"},
    {name="Eel", min=15, max=60, weight=4, strength=12, rarity="Common"},
    {name="Flounder", min=25, max=70, weight=6, strength=18, rarity="Common"},
    {name="Cod", min=50, max=120, weight=14, strength=22, rarity="Common"},
    {name="Herring", min=10, max=30, weight=3, strength=8, rarity="Common"},
    {name="Tilapia", min=20, max=60, weight=8, strength=15, rarity="Common"},
    {name="Mullet", min=30, max=90, weight=10, strength=20, rarity="Common"},
    {name="Rockfish", min=60, max=130, weight=12, strength=25, rarity="Common"},
    {name="Clownfish", min=2, max=10, weight=0.5, strength=1, rarity="Common"},
    {name="Butterfish", min=10, max=35, weight=4, strength=8, rarity="Common"},
    {name="Sardine", min=5, max=15, weight=1, strength=2, rarity="Common"},
    {name="Anchovy", min=3, max=12, weight=0.5, strength=1, rarity="Common"},
    {name="Bluegill", min=5, max=25, weight=2, strength=5, rarity="Common"},
    {name="Sunfish", min=8, max=30, weight=3, strength=6, rarity="Common"},
    {name="Shiner", min=2, max=8, weight=0.5, strength=1, rarity="Common"},
    {name="Whitefish", min=20, max=55, weight=6, strength=15, rarity="Common"},
    {name="Yellow Perch", min=15, max=45, weight=5, strength=12, rarity="Common"},
    {name="Bluefish", min=40, max=100, weight=10, strength=20, rarity="Common"},
    {name="Crappie", min=8, max=25, weight=2, strength=5, rarity="Common"},
    {name="Round Goby", min=3, max=12, weight=1, strength=2, rarity="Common"},
    {name="Rainbow Minnow", min=2, max=10, weight=0.5, strength=1, rarity="Common"},
    
    -- UNCOMMON
    {name="Catfish", min=90, max=200, weight=12, strength=45, rarity="Uncommon"},
    {name="Pike", min=80, max=180, weight=18, strength=40, rarity="Uncommon"},
    {name="Grouper", min=100, max=250, weight=20, strength=45, rarity="Uncommon"},
    {name="Octopus", min=20, max=60, weight=6, strength=25, rarity="Uncommon"},
    {name="Cuttlefish", min=15, max=50, weight=5, strength=18, rarity="Uncommon"},
    {name="Scorpionfish", min=50, max=120, weight=10, strength=30, rarity="Uncommon"},
    {name="Piranha", min=15, max=40, weight=3, strength=20, rarity="Uncommon"},
    {name="Rainbow Trout", min=80, max=180, weight=15, strength=35, rarity="Uncommon"},
    {name="Red Snapper", min=100, max=250, weight=10, strength=45, rarity="Uncommon"},
    {name="Lobster", min=30, max=80, weight=2, strength=20, rarity="Uncommon"},
    {name="Ice Eel", min=80, max=200, weight=4, strength=35, rarity="Uncommon"},
    {name="Firefish", min=100, max=250, weight=4, strength=40, rarity="Uncommon"},
    {name="Stonefish", min=60, max=180, weight=8, strength=45, rarity="Uncommon"},
    {name="Barbel", min=40, max=120, weight=6, strength=35, rarity="Uncommon"},
    
    -- RARE
    {name="Tuna", min=300, max=550, weight=6, strength=60, rarity="Rare"},
    {name="Swordfish", min=500, max=1200, weight=5, strength=70, rarity="Rare"},
    {name="Marlin", min=600, max=1500, weight=4, strength=75, rarity="Rare"},
    {name="Barracuda", min=200, max=400, weight=8, strength=55, rarity="Rare"},
    {name="Sturgeon", min=400, max=900, weight=10, strength=65, rarity="Rare"},
    {name="Wahoo", min=400, max=900, weight=4, strength=65, rarity="Rare"},
    {name="King Crab", min=200, max=400, weight=3, strength=50, rarity="Rare"},
    {name="Mahi Mahi", min=250, max=600, weight=5, strength=55, rarity="Rare"},
    {name="Golden Carp", min=500, max=1500, weight=2, strength=60, rarity="Rare"},
    {name="Crystal Snapper", min=150, max=400, weight=3, strength=50, rarity="Rare"},
    
    -- EPIC
    {name="Shark", min=1200, max=3000, weight=1, strength=85, rarity="Epic"},
    {name="Bluefin Tuna", min=800, max=2000, weight=3, strength=80, rarity="Epic"},
    {name="Anglerfish", min=300, max=800, weight=2, strength=70, rarity="Epic"},
    {name="Rainbow Shark", min=1500, max=4000, weight=1, strength=90, rarity="Epic"},
    {name="Diamond Fish", min=1000, max=3000, weight=1, strength=95, rarity="Epic"},
    {name="Shadowfin", min=300, max=700, weight=2, strength=70, rarity="Epic"},
    
    -- LEGENDARY / MYTHICAL
    {name="Megalodon", min=5000, max=15000, weight=1, strength=120, rarity="Legendary"},
    {name="Kraken", min=10000, max=30000, weight=1, strength=150, rarity="Legendary"},
    {name="Leviathan", min=8000, max=20000, weight=1, strength=140, rarity="Legendary"},
    {name="Sea Serpent", min=4000, max=12000, weight=2, strength=110, rarity="Legendary"},
    {name="Ghost Fish", min=200, max=600, weight=1, strength=80, rarity="Legendary"},
    
    -- EXTRA VARIANTS / FUN
    {name="Glowing Angler", min=200, max=500, weight=2, strength=70, rarity="Epic"},
    {name="Rainbow Minnow", min=2, max=10, weight=0.5, strength=1, rarity="Common"},
    {name="Electric Eel", min=100, max=300, weight=4, strength=60, rarity="Rare"},
    {name="Phantom Bass", min=200, max=400, weight=3, strength=65, rarity="Epic"},
    {name="Meteor Fish", min=500, max=1500, weight=1, strength=80, rarity="Legendary"},
    {name="Cursed Trout", min=50, max=150, weight=5, strength=30, rarity="Uncommon"},
    {name="Golden Trout", min=300, max=700, weight=3, strength=50, rarity="Rare"},
}
return fishList
